import { Booking } from './types'
import { format, addDays, subDays } from 'date-fns'

const today = new Date()
const todayStr = format(today, 'yyyy-MM-dd')
const tomorrowStr = format(addDays(today, 1), 'yyyy-MM-dd')
const nextWeekStr = format(addDays(today, 7), 'yyyy-MM-dd')
const yesterdayStr = format(subDays(today, 1), 'yyyy-MM-dd')

export const initialBookings: Booking[] = [
  {
    id: '1',
    mcName: 'Misthy',
    contentName: 'Review son mới tháng 7',
    type: 'Daily content',
    sow: 'Video',
    platforms: ['TikTok', 'YouTube'],
    date: todayStr,
    startTime: '09:00',
    endTime: '11:00',
    cameraCount: 2,
    micCount: 2,
    hasTikTokCamera: true,
    hasActionCam: false,
    hasGimbal: true,
    hasHandheldLight: false,
    location: 'Studio A',
    notes: 'Cần chuẩn bị backdrop màu hồng',
    status: 'approved',
    assignedCameramen: ['Đạt', 'Giang'],
    createdBy: '4',
    createdByName: 'Trần Thị A',
    isModified: false,
    createdAt: format(subDays(today, 3), "yyyy-MM-dd'T'HH:mm:ss"),
    updatedAt: format(subDays(today, 1), "yyyy-MM-dd'T'HH:mm:ss"),
  },
  {
    id: '2',
    mcName: 'Nam Phương',
    contentName: 'Livestream bán hàng Shopee',
    type: 'Brand',
    sow: 'Livestream',
    platforms: ['Shopee', 'Facebook'],
    date: todayStr,
    startTime: '14:00',
    endTime: '17:00',
    cameraCount: 3,
    micCount: 3,
    hasTikTokCamera: false,
    hasActionCam: true,
    hasGimbal: false,
    hasHandheldLight: true,
    location: 'Studio B',
    notes: 'Sản phẩm: Son, kem nền',
    status: 'pending',
    assignedCameramen: [],
    createdBy: '5',
    createdByName: 'Nguyễn Văn B',
    isModified: false,
    createdAt: format(subDays(today, 2), "yyyy-MM-dd'T'HH:mm:ss"),
    updatedAt: format(subDays(today, 2), "yyyy-MM-dd'T'HH:mm:ss"),
  },
  {
    id: '3',
    mcName: 'Brand',
    brandName: 'Cocoon',
    contentName: 'Shoot ảnh sản phẩm mới',
    type: 'Brand',
    sow: 'Photoshoot',
    platforms: ['Facebook', 'TikTok'],
    date: tomorrowStr,
    startTime: '10:00',
    endTime: '16:00',
    cameraCount: 2,
    micCount: 1,
    hasTikTokCamera: false,
    hasActionCam: false,
    hasGimbal: false,
    hasHandheldLight: true,
    location: 'Studio A',
    notes: 'Chụp 20 sản phẩm, cần ánh sáng tự nhiên',
    status: 'approved',
    assignedCameramen: ['Huy', 'Hiệu'],
    createdBy: '4',
    createdByName: 'Trần Thị A',
    isModified: false,
    createdAt: format(subDays(today, 5), "yyyy-MM-dd'T'HH:mm:ss"),
    updatedAt: format(subDays(today, 4), "yyyy-MM-dd'T'HH:mm:ss"),
  },
  {
    id: '4',
    mcName: 'Misthy',
    contentName: 'Q&A fans',
    type: 'Daily content',
    sow: 'Video',
    platforms: ['TikTok'],
    date: nextWeekStr,
    startTime: '13:00',
    endTime: '15:00',
    cameraCount: 1,
    micCount: 1,
    hasTikTokCamera: true,
    hasActionCam: false,
    hasGimbal: true,
    hasHandheldLight: false,
    location: 'Studio C',
    status: 'pending',
    assignedCameramen: [],
    createdBy: '5',
    createdByName: 'Nguyễn Văn B',
    isModified: false,
    createdAt: format(subDays(today, 1), "yyyy-MM-dd'T'HH:mm:ss"),
    updatedAt: format(subDays(today, 1), "yyyy-MM-dd'T'HH:mm:ss"),
  },
  {
    id: '5',
    mcName: 'Nam Phương',
    contentName: 'Tutorial trang điểm',
    type: 'SPS',
    sow: 'Video',
    platforms: ['YouTube', 'TikTok'],
    date: yesterdayStr,
    startTime: '09:00',
    endTime: '12:00',
    cameraCount: 2,
    micCount: 2,
    hasTikTokCamera: false,
    hasActionCam: true,
    hasGimbal: false,
    hasHandheldLight: true,
    location: 'Studio A',
    status: 'approved',
    assignedCameramen: ['Thức', 'Hùng'],
    createdBy: '4',
    createdByName: 'Trần Thị A',
    isModified: true,
    createdAt: format(subDays(today, 7), "yyyy-MM-dd'T'HH:mm:ss"),
    updatedAt: format(today, "yyyy-MM-dd'T'HH:mm:ss"),
  },
  {
    id: '6',
    mcName: 'Brand',
    brandName: 'L\'Oreal',
    contentName: 'PR campaign video',
    type: 'Brand',
    sow: 'Video',
    platforms: ['YouTube', 'Facebook'],
    date: format(addDays(today, 3), 'yyyy-MM-dd'),
    startTime: '08:00',
    endTime: '18:00',
    cameraCount: 4,
    micCount: 4,
    hasTikTokCamera: true,
    hasActionCam: true,
    hasGimbal: true,
    hasHandheldLight: true,
    location: 'Outdoor - Công viên',
    notes: 'Cần di chuyển nhiều location, chuẩn bị xe',
    status: 'pending',
    assignedCameramen: [],
    createdBy: '4',
    createdByName: 'Trần Thị A',
    isModified: false,
    createdAt: format(today, "yyyy-MM-dd'T'HH:mm:ss"),
    updatedAt: format(today, "yyyy-MM-dd'T'HH:mm:ss"),
  },
  {
    id: '7',
    mcName: 'Misthy',
    contentName: 'Unboxing sản phẩm',
    type: 'Daily content',
    sow: 'Video',
    platforms: ['TikTok', 'YouTube'],
    date: format(addDays(today, 5), 'yyyy-MM-dd'),
    startTime: '11:00',
    endTime: '13:00',
    cameraCount: 1,
    micCount: 1,
    hasTikTokCamera: true,
    hasActionCam: false,
    hasGimbal: false,
    hasHandheldLight: false,
    location: 'Studio B',
    status: 'approved',
    assignedCameramen: ['Tabo'],
    createdBy: '5',
    createdByName: 'Nguyễn Văn B',
    isModified: false,
    createdAt: format(subDays(today, 4), "yyyy-MM-dd'T'HH:mm:ss"),
    updatedAt: format(subDays(today, 2), "yyyy-MM-dd'T'HH:mm:ss"),
  },
]
